### PR TITLE
Votebombs-b-gone!

### PR DESCRIPTION
**Pull request by rikosaku**
I wrote this patch after looking at r3muxd's pitiful mess of a patch. I have tested it to work and not show any weird side effects, and it stops votebombs as far as i know (~~I was actually planning to be an asshole and only send a message to the vote bomber causing only *them* to crash, but that didn't work too good.~~)

Anyways, I tried at least.

### CODE REVIEW

**Comment by dr3murr** [comment]
that's good, but that's per user, right? what if i reconnect whenever i reach the vote limit?
(edit: nvm, just saw the TODO)

**Comment by dr3murr** [comment]
i'd move it to ipdata before it gets merged but other than that 👍

**Comment by rikosaku** [comment]
`that's good, but that's per user, right? what if i reconnect whenever i reach the vote limit?`
while yes, you could do that, you never get any notification that you hit the limit (for what i was planning to do which is only send a message to votebomber, it would give you an notification). you'd have to guess if you did in fact hit the limit, which isn't as easy as it sounds unless you keep listening for vote instructions

**Comment by dr3murr** [comment]
also maybe mute the user for attempting to lastmeasure
(yeah, i made that comment before i saw the TODO sorry)

**Comment by dr3murr** [comment]
i'd make it so that you can vote VoteTime/database_.Configuration.ChatRateCount number of times per vote (so basically once per second)

**Comment by dr3murr** [comment]
also, why does the client use 100% cpu when lastmeasure's happening? that'd probably be a better idea to check (since HYPOTHETICALLY if you have enough IPs you could lastmeasure)

**Comment by dr3murr** [comment]
(you could do something like scrape a really big list of websocket proxies and spam from there, but to block that i'd just use firehol/firehol like what should have been done a long time ago)

**Comment by dr3murr** [comment]
also this is a really minor nitpick, but why `voted_limit`? why not `reached_vote_limit`?
that way you can change `if(user.voted_limit == false)` to the much more readable `if(!reached_vote_limit)`, and `if(user.voted_amount) { user.voted_amount = 0; }` to `user.reached_vote_limit && user.voted_amount = 0;` (if that's even valid C++

**Comment by dartzcn** [comment]
Looks good here. Will be testing this shortly

**Pull request merged**
