### PR TITLE
Fixes some stuff, makes it build on windows...

### PR DESCRIPTION
**Pull request by yellows111**
i mean its a 20mb static binary right now but its not that bad right???

Also, no startup message?

### CODE REVIEW

**Comment by yellows111** [comment]
For context, what it was doing before is screaming about __declspec not being able to find winsock2's libraries.

**Comment by modeco80** [comment]
remove the cmake shit from this pr, a lot of it is needlessly crusty and ive already done it more properly on HEAD

**Comment by yellows111** [comment]
*what* cmake stuff?, just edits to core cmake files? i mean sure, just not editing the gitignore will make git complain about "uncommited files" *constantly*

**Comment by yellows111** [comment]
#109

**Comment by modeco80** [comment]
>just not editing the gitignore will make git complain about "uncommited files" constantly

use `build` as your build dir then. there is a reason it's ignored as well as IDEA/Clion cmake build dirs

(either that or don't go `git commit -a` ing all the time)

**Comment by yellows111** [comment]
i've started to do build directories instead of `cmake .`'s.

also i've vetted my commits since a while back in case of file leakage. i'd use `-a` if i know its safe for every file in the "to commit" list is fine.

**Pull request closed without merging**
