### PR TITLE
Stop kit and username scripts

### PR DESCRIPTION
**Pull request by 6-9-6-9**
Ratelimits mouse movements and username changes.

### CODE REVIEW

**Comment by ghost** [comment]
@computernewb daily reminder to merge pr

**Comment by modeco80** [comment]
does your compiler libstdc++ version not support `std::stoi` or did you choose to use the internal namespace (either way i'd just change to stoi since it will most likely not flail and die even though gcc is the project-wide compiler)

**Comment by ghost** [comment]
@computernewb daily reminder to merge pr

**Comment by ghost** [comment]
@computernewb daily reminder to merge pr

**Comment by ghost** [comment]
@computernewb daily reminder to merge pr

**Comment by ghost** [comment]
@computernewb daily reminder to merge the pr

**Comment by forkiesassds** [comment]
@computernewb daily reminder to merge the pr

**Comment by ghost** [comment]
@computernewb daily reminder to merge pr

**Comment by ghost** [comment]
@computernewb daily reminder to merge pr

**Comment by ghost** [comment]
@computernewb daily reminder to merge pr (i missed a day, oops)

**Comment by ghost** [comment]
@computernewb daily reminder: merge pr

**Comment by ghost** [comment]
@computernewb daily reminder: merge pr (i'm finally back to fully existing, so i should no longer miss days from now on)

**Comment by ghost** [comment]
@computernewb daily reminder to merge pr

**Comment by ghost** [comment]
@computernewb daily reminder: merge pr

**Comment by ghost** [comment]
@computernewb merge

**Comment by ghost** [comment]
@computernewb merge

**Comment by ghost** [comment]
@computernewb merge

**Comment by ghost** [comment]
@computernewb merge

**Comment by ghost** [comment]
@computernewb daily reminder to merge pr

**Comment by ghost** [comment]
@computernewb merge

**Comment by ghost** [comment]
@computernewb

**Comment by ghost** [comment]
@computernewb m

**Comment by ghost** [comment]
@computernewb merge

**Comment by ghost** [comment]
@computernewb do

**Comment by ghost** [comment]
@computernewb the

**Comment by ghost** [comment]
@computernewb pr

**Comment by ghost** [comment]
@computernewb it

**Comment by ghost** [comment]
@computernewb needs

**Comment by ghost** [comment]
@computernewb to

**Comment by ghost** [comment]
@computernewb be

**Comment by ghost** [comment]
@computernewb merged

**Comment by ghost** [comment]
@computernewb as

**Comment by ghost** [comment]
@computernewb soon

**Comment by ghost** [comment]
@computernewb as

**Comment by ghost** [comment]
@computernewb possible

**Comment by ghost** [comment]
@computernewb do it

**Comment by modeco80** [comment]
Shut the fuck up jesus christ

-------- Original Message --------

**Comment by ghost** [comment]
@modeco80 no, i will continue telling dartz about how the pr should be merged on a daily basis, with that said:

@computernewb merge pr

**Comment by ghost** [comment]
@computernewb merge

**Comment by ghost** [comment]
@computernewb merge

**Comment by ghost** [comment]
@computernewb

**Comment by ghost** [comment]
@computernewb

**Comment by ghost** [comment]
@computernewb

**Comment by ghost** [comment]
@computernewb

**Comment by ghost** [comment]
@computernewb

**Comment by ghost** [comment]
@computernewb

**Comment by ghost** [comment]
@computernewb

**Comment by ghost** [comment]
@computernewb

**Comment by ghost** [comment]
@computernewb

**Comment by ghost** [comment]
@computernewb

**Comment by ghost** [comment]
@computernewb

**Comment by ghost** [comment]
@computernewb

**Comment by ghost** [comment]
@computernewb

**Comment by ghost** [comment]
@computernewb

**Comment by ghost** [comment]
@computernewb

**Comment by ghost** [comment]
@computernewb

**Comment by ghost** [comment]
Holy fuck.... it's over.... i've been freed...

**Pull request merged**
