### PR TITLE
HTTP for 1.3.0 via MDMCK10

### PR DESCRIPTION
**Pull request by yellows111**
fixed some lines not saying 1.3.0 and some other things mostly related to building, speaking of such

```cpp
"childprocess errors have been fixed"
```

### CODE REVIEW

**Comment by modeco80** [comment]
I'll probably be internally merging this and most 1.3.0 prs until a "release" stage is near

**Comment by modeco80** [comment]
Actually uhhh.. hmm.... I dunno. I looked at this PR a bit closer (I haven't had the chance to) and uh... I have a few gripes:

- The usage of `dynamic_body` for 301's should be `http::response<empty_body>` since redirects don't need any body at all.

- On that tangent,`dynamic_body` usage doesn't really even make sense. `string_body` would work fine in the other cases and allow assignment ala `res.body() = "thing";`, which I assume you're trying to emulate (Ideally speaking, we'd use `fmt` to format html template pages).

- [**THIS ONE IS PRETTY MUCH WHY I AM NOT (INT)MERGING**] This PR mixes async/sync primitives when writing (Lifetime is sort of confusing yeah, but the advanced-server example shows you how to do this better with a response queue, and if you don't like the Boost code style [see here where I've actually rewritten said code.](https://github.com/modeco80/pixelboard/blob/master/src/websocket/HttpSession.cpp)), which is a giant no-no, and I'm vaguely suprised it doesn't fall down the stairs like it does when doing this for websockets. Either way, this is still bad.

- `stat()`? Prefer `std::filesystem` for portability (and the code is cleaner cause you don't need a stat structure everywhere and a conditional include.)

I'm working on a slightly less crusty thing using beast, and for a bit I was actually trying to cleanup websocketmm. But honestly once that project is done I'll probably just replace mm with this stuff, cause I'm also trying to IWYU a bit better

**Comment by modeco80** [comment]
Decision:

I'm going to slot in the PixelBoard WebSocket library when it's done (which will probably be tonight or sometime tomorrow after some testing if I'm lucky :p), rewriting the existing cvm code to use pixelboard::websocket in the process.

(probably going to revert the Boost.Process changes as well, cause boost process doesn't wanna boost WORK atm)

Unfortunately that also means I'm closing this PR, since I'll be the one addressing it now. :(

**Comment by yellows111** [comment]
Didn't read this until now, however theres still *some* parts of this branch that aren't too hacky outside of what they're normally should be (mkconfig fixes for win64 and such)

Other than that, sorry about the HTTP side, was kind of a quick and dirty hack in retrospect, I agree that it should of been improved on.

On the side, we should promote clang64 over mingw64 if we're going towards CMake, which I should of said in a "Revisit implementing CMake" issue, but whatever, as clang64 has vendor-specific files related to the dependancies we use in CMake. (t. jpeg-turbo-config.cmake).

Speaking of CMake, practically none of the main distros that have CMake/clang support don't have boost-config.cmake (or whatever it's called) yet.

**Comment by yellows111** [comment]
I'm probably going to `git cherry-pick` out the non HTTP commits and then for mixed commits i'll weed out the HTTP side of any affected until it's clean.

After that I'll make a new PR containing that branch?

**Pull request closed without merging**
